export type ChatScrollOwner = "auto" | "user" | "anchor" | "jump";

export type ChatScrollState = {
  owner: ChatScrollOwner;
  newBelowCount: number;
};

export type ChatScrollEvent =
  | { type: "content-growth"; added?: number }
  | { type: "user-scroll-up" }
  | { type: "user-scroll-down"; atBottom?: boolean }
  | { type: "user-reached-bottom" }
  | { type: "anchor-start" }
  | { type: "anchor-end"; atBottom?: boolean }
  | { type: "jump-start" }
  | { type: "jump-end"; atBottom?: boolean };

export type ChatScrollReduction = {
  state: ChatScrollState;
  effect: "none" | "pin-bottom";
};

export function createChatScrollState(): ChatScrollState {
  return { owner: "auto", newBelowCount: 0 };
}

function addedCount(value: number | undefined): number {
  if (!Number.isFinite(value) || value == null) return 1;
  return Math.max(0, Math.floor(value));
}

function withOwner(state: ChatScrollState, owner: ChatScrollOwner): ChatScrollState {
  return { owner, newBelowCount: state.newBelowCount };
}

function finishTransientOwner(state: ChatScrollState, atBottom: boolean | undefined): ChatScrollReduction {
  if (atBottom) return { state: { owner: "auto", newBelowCount: 0 }, effect: "pin-bottom" };
  return { state: { owner: "user", newBelowCount: state.newBelowCount }, effect: "none" };
}

export function reduceChatScrollState(
  state: ChatScrollState = createChatScrollState(),
  event: ChatScrollEvent,
): ChatScrollReduction {
  switch (event.type) {
    case "content-growth": {
      const added = addedCount(event.added);
      if (state.owner === "auto") {
        return { state: { owner: "auto", newBelowCount: 0 }, effect: "pin-bottom" };
      }
      return {
        state: { owner: state.owner, newBelowCount: state.newBelowCount + added },
        effect: "none",
      };
    }
    case "user-scroll-up":
      return { state: withOwner(state, "user"), effect: "none" };
    case "user-scroll-down":
      return event.atBottom ? { state: { owner: "auto", newBelowCount: 0 }, effect: "pin-bottom" } : { state: withOwner(state, "user"), effect: "none" };
    case "user-reached-bottom":
      return { state: { owner: "auto", newBelowCount: 0 }, effect: "pin-bottom" };
    case "anchor-start":
      return { state: withOwner(state, "anchor"), effect: "none" };
    case "anchor-end":
      return finishTransientOwner(state, Boolean(event.atBottom));
    case "jump-start":
      return { state: withOwner(state, "jump"), effect: "none" };
    case "jump-end":
      return finishTransientOwner(state, Boolean(event.atBottom));
    default:
      return { state, effect: "none" };
  }
}

export type FrameSchedulerOptions = {
  requestFrame?: (callback: () => void) => number;
  cancelFrame?: (id: number) => void;
  run: () => void;
};

/** Coalesce all bottom-pin requests generated by one render turn. */
export function createFrameScheduler(options: FrameSchedulerOptions) {
  const requestFrame = options.requestFrame ?? ((callback) => requestAnimationFrame(callback));
  const cancelFrame = options.cancelFrame ?? ((id) => cancelAnimationFrame(id));
  let frameId: number | null = null;

  return {
    schedule() {
      if (frameId !== null) return;
      frameId = requestFrame(() => {
        const completedFrameId = frameId;
        frameId = null;
        // Clear the scheduler-owned handle before running user code. This also
        // keeps deterministic requestFrame test doubles from retaining stale work.
        if (completedFrameId !== null) cancelFrame(completedFrameId);
        options.run();
      });
    },
    cancel() {
      if (frameId === null) return;
      cancelFrame(frameId);
      frameId = null;
    },
    get scheduled() {
      return frameId !== null;
    },
  };
}
