// 聊天滚动策略（精简版）。
//
// 设计原则：滚动所有权是一个布尔——followingBottom（是否跟随底部）。
// 只有用户的原始输入事件（上滚滚轮、拖滚动条、触摸滑动、上翻按键、
// 跳转消息）能脱离跟随；只有显式动作（发送消息、点"回到底部"、
// 打开会话）能恢复跟随。scroll 事件本身永远不改变所有权，内容高度
// 变化（流式收敛、卡片折叠）因此不可能误判并劫持视口。
// 历史加载与前后台恢复是一次性操作，不再持有长期 owner 状态。

export type GrowthEffect =
  | { type: "none" }
  | { type: "pin" }
  | { type: "count"; added: number };

/** 内容增长时的唯一决策：跟随时贴底，否则累计"下方新消息"计数。 */
export function computeGrowthEffect(followingBottom: boolean, added: number | undefined): GrowthEffect {
  const count = !Number.isFinite(added) || added == null ? 1 : Math.max(0, Math.floor(added));
  if (count === 0) return { type: "none" };
  if (followingBottom) return { type: "pin" };
  return { type: "count", added: count };
}

export type TopLoadCheck = {
  scrollTop: number;
  threshold: number;
  loading: boolean;
  dragging: boolean;
  backgrounded: boolean;
  suppressed: boolean;
};

/** 顶部自动加载的唯一判定：滚动已停止（由调用方防抖保证）且仍停在顶部。 */
export function shouldTriggerTopLoad(check: TopLoadCheck): boolean {
  if (check.loading || check.dragging || check.backgrounded || check.suppressed) return false;
  return check.scrollTop <= check.threshold;
}

export type FrameSchedulerOptions = {
  requestFrame?: (callback: () => void) => number;
  cancelFrame?: (id: number) => void;
  run: () => void;
};

/** Coalesce all bottom-pin requests generated by one render turn. */
export function createFrameScheduler(options: FrameSchedulerOptions) {
  const requestFrame = options.requestFrame ?? ((callback) => requestAnimationFrame(callback));
  const cancelFrame = options.cancelFrame ?? ((id) => cancelAnimationFrame(id));
  let frameId: number | null = null;

  return {
    schedule() {
      if (frameId !== null) return;
      frameId = requestFrame(() => {
        const completedFrameId = frameId;
        frameId = null;
        // Clear the scheduler-owned handle before running user code. This also
        // keeps deterministic requestFrame test doubles from retaining stale work.
        if (completedFrameId !== null) cancelFrame(completedFrameId);
        options.run();
      });
    },
    cancel() {
      if (frameId === null) return;
      cancelFrame(frameId);
      frameId = null;
    },
    get scheduled() {
      return frameId !== null;
    },
  };
}
